### ISSUE TITLE
Normative: Permit relatedYear and yearName in output

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#9]
Missing MDN documentation

**Comment by bkardell** [comment]
added this section https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts#Named_Years_and_Mixed_calendars - I would appreciate scrutiny on whether you feel like I've understood and represented this properly because I feel like the design feels a little wonky to me and part of that may be because there are bits I'm missing still.. Also updated the output props but this isn't really much.

**Comment by bkardell** [comment]
I've done a few rounds on this and back and forth with @littledan and @caiolima - I'm going to mark this as complete...
